apiVersion: v1
kind: BuildConfig
metadata:
  name: ruby-mysql-app-pipeline
spec:
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: <your fork here>
      ref: <your branch here if applicable>
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
  output:
    to:
      kind: ImageStreamTag
      name: 'ruby-mysql-app:latest'
status:
